-- カフェマスターチェーン と 取得対象 のテーブルを指定
\set chaintbl   :schema'.mst_cafe_chain'
\set targettbl  :schema'.mst_fetch_target_chain'

-- 検索が正しいレコードのみを、経度・緯度・対象駅・チェーン でまとめる
WITH tmp1 AS (
    SELECT
        search_lat,
        search_lon,
        target_station_name,
        search_name
    FROM :schema.tmp_add_search_check
    WHERE search_check_flag = 1
    GROUP BY search_lat, search_lon, target_station_name, search_name
),
-- 経度・緯度・チェーン ごとに、チェーンの有無の表を作成
tmp2 AS (
    SELECT
        search_lat,
        search_lon,
        target_station_name,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  1) THEN 1 ELSE 0 END AS tmp_cflag01,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  2) THEN 1 ELSE 0 END AS tmp_cflag02,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  3) THEN 1 ELSE 0 END AS tmp_cflag03,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  4) THEN 1 ELSE 0 END AS tmp_cflag04,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  5) THEN 1 ELSE 0 END AS tmp_cflag05,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  6) THEN 1 ELSE 0 END AS tmp_cflag06,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  7) THEN 1 ELSE 0 END AS tmp_cflag07,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  8) THEN 1 ELSE 0 END AS tmp_cflag08,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id =  9) THEN 1 ELSE 0 END AS tmp_cflag09,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 10) THEN 1 ELSE 0 END AS tmp_cflag10,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 11) THEN 1 ELSE 0 END AS tmp_cflag11,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 12) THEN 1 ELSE 0 END AS tmp_cflag12,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 13) THEN 1 ELSE 0 END AS tmp_cflag13,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 14) THEN 1 ELSE 0 END AS tmp_cflag14,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 15) THEN 1 ELSE 0 END AS tmp_cflag15,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 16) THEN 1 ELSE 0 END AS tmp_cflag16,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 17) THEN 1 ELSE 0 END AS tmp_cflag17,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 18) THEN 1 ELSE 0 END AS tmp_cflag18,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 19) THEN 1 ELSE 0 END AS tmp_cflag19,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 20) THEN 1 ELSE 0 END AS tmp_cflag20,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 21) THEN 1 ELSE 0 END AS tmp_cflag21,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 22) THEN 1 ELSE 0 END AS tmp_cflag22,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 23) THEN 1 ELSE 0 END AS tmp_cflag23,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 24) THEN 1 ELSE 0 END AS tmp_cflag24,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 25) THEN 1 ELSE 0 END AS tmp_cflag25,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 26) THEN 1 ELSE 0 END AS tmp_cflag26,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 27) THEN 1 ELSE 0 END AS tmp_cflag27,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 28) THEN 1 ELSE 0 END AS tmp_cflag28,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 29) THEN 1 ELSE 0 END AS tmp_cflag29,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 30) THEN 1 ELSE 0 END AS tmp_cflag30,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 31) THEN 1 ELSE 0 END AS tmp_cflag31,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 32) THEN 1 ELSE 0 END AS tmp_cflag32,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 33) THEN 1 ELSE 0 END AS tmp_cflag33,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 34) THEN 1 ELSE 0 END AS tmp_cflag34,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 35) THEN 1 ELSE 0 END AS tmp_cflag35,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 36) THEN 1 ELSE 0 END AS tmp_cflag36,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 37) THEN 1 ELSE 0 END AS tmp_cflag37,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 38) THEN 1 ELSE 0 END AS tmp_cflag38,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 39) THEN 1 ELSE 0 END AS tmp_cflag39,
        CASE WHEN search_name = (SELECT search_name FROM :chaintbl WHERE chain_id = 40) THEN 1 ELSE 0 END AS tmp_cflag40
    FROM tmp1
),
-- チェーンの有無の表を 緯度・経度 でまとめる （検索していないチェーンは NULL）
tmp3 AS (
    SELECT
        search_lat,
        search_lon,
        target_station_name,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  1) IS NULL THEN NULL ELSE SUM(tmp_cflag01) END AS cflag01,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  2) IS NULL THEN NULL ELSE SUM(tmp_cflag02) END AS cflag02,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  3) IS NULL THEN NULL ELSE SUM(tmp_cflag03) END AS cflag03,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  4) IS NULL THEN NULL ELSE SUM(tmp_cflag04) END AS cflag04,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  5) IS NULL THEN NULL ELSE SUM(tmp_cflag05) END AS cflag05,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  6) IS NULL THEN NULL ELSE SUM(tmp_cflag06) END AS cflag06,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  7) IS NULL THEN NULL ELSE SUM(tmp_cflag07) END AS cflag07,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  8) IS NULL THEN NULL ELSE SUM(tmp_cflag08) END AS cflag08,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id =  9) IS NULL THEN NULL ELSE SUM(tmp_cflag09) END AS cflag09,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 10) IS NULL THEN NULL ELSE SUM(tmp_cflag10) END AS cflag10,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 11) IS NULL THEN NULL ELSE SUM(tmp_cflag11) END AS cflag11,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 12) IS NULL THEN NULL ELSE SUM(tmp_cflag12) END AS cflag12,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 13) IS NULL THEN NULL ELSE SUM(tmp_cflag13) END AS cflag13,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 14) IS NULL THEN NULL ELSE SUM(tmp_cflag14) END AS cflag14,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 15) IS NULL THEN NULL ELSE SUM(tmp_cflag15) END AS cflag15,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 16) IS NULL THEN NULL ELSE SUM(tmp_cflag16) END AS cflag16,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 17) IS NULL THEN NULL ELSE SUM(tmp_cflag17) END AS cflag17,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 18) IS NULL THEN NULL ELSE SUM(tmp_cflag18) END AS cflag18,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 19) IS NULL THEN NULL ELSE SUM(tmp_cflag19) END AS cflag19,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 20) IS NULL THEN NULL ELSE SUM(tmp_cflag20) END AS cflag20,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 21) IS NULL THEN NULL ELSE SUM(tmp_cflag21) END AS cflag21,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 22) IS NULL THEN NULL ELSE SUM(tmp_cflag22) END AS cflag22,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 23) IS NULL THEN NULL ELSE SUM(tmp_cflag23) END AS cflag23,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 24) IS NULL THEN NULL ELSE SUM(tmp_cflag24) END AS cflag24,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 25) IS NULL THEN NULL ELSE SUM(tmp_cflag25) END AS cflag25,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 26) IS NULL THEN NULL ELSE SUM(tmp_cflag26) END AS cflag26,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 27) IS NULL THEN NULL ELSE SUM(tmp_cflag27) END AS cflag27,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 28) IS NULL THEN NULL ELSE SUM(tmp_cflag28) END AS cflag28,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 29) IS NULL THEN NULL ELSE SUM(tmp_cflag29) END AS cflag29,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 30) IS NULL THEN NULL ELSE SUM(tmp_cflag30) END AS cflag30,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 31) IS NULL THEN NULL ELSE SUM(tmp_cflag31) END AS cflag31,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 32) IS NULL THEN NULL ELSE SUM(tmp_cflag32) END AS cflag32,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 33) IS NULL THEN NULL ELSE SUM(tmp_cflag33) END AS cflag33,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 34) IS NULL THEN NULL ELSE SUM(tmp_cflag34) END AS cflag34,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 35) IS NULL THEN NULL ELSE SUM(tmp_cflag35) END AS cflag35,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 36) IS NULL THEN NULL ELSE SUM(tmp_cflag36) END AS cflag36,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 37) IS NULL THEN NULL ELSE SUM(tmp_cflag37) END AS cflag37,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 38) IS NULL THEN NULL ELSE SUM(tmp_cflag38) END AS cflag38,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 39) IS NULL THEN NULL ELSE SUM(tmp_cflag39) END AS cflag39,
        CASE WHEN (SELECT 1 FROM :targettbl WHERE target_chain_id = 40) IS NULL THEN NULL ELSE SUM(tmp_cflag40) END AS cflag40
    FROM tmp2
    GROUP BY search_lat, search_lon, target_station_name
)

-- 駅カフェ情報作成テーブルへの挿入
INSERT INTO :schema.tmp_create_stationcafe_info (
    search_lat,
    search_lon,
    target_station_name,
    cflag01,
    cflag02,
    cflag03,
    cflag04,
    cflag05,
    cflag06,
    cflag07,
    cflag08,
    cflag09,
    cflag10,
    cflag11,
    cflag12,
    cflag13,
    cflag14,
    cflag15,
    cflag16,
    cflag17,
    cflag18,
    cflag19,
    cflag20,
    cflag21,
    cflag22,
    cflag23,
    cflag24,
    cflag25,
    cflag26,
    cflag27,
    cflag28,
    cflag29,
    cflag30,
    cflag31,
    cflag32,
    cflag33,
    cflag34,
    cflag35,
    cflag36,
    cflag37,
    cflag38,
    cflag39,
    cflag40,
    update_datetime
)
SELECT
    search_lat,
    search_lon,
    target_station_name,
    cflag01,
    cflag02,
    cflag03,
    cflag04,
    cflag05,
    cflag06,
    cflag07,
    cflag08,
    cflag09,
    cflag10,
    cflag11,
    cflag12,
    cflag13,
    cflag14,
    cflag15,
    cflag16,
    cflag17,
    cflag18,
    cflag19,
    cflag20,
    cflag21,
    cflag22,
    cflag23,
    cflag24,
    cflag25,
    cflag26,
    cflag27,
    cflag28,
    cflag29,
    cflag30,
    cflag31,
    cflag32,
    cflag33,
    cflag34,
    cflag35,
    cflag36,
    cflag37,
    cflag38,
    cflag39,
    cflag40,
    NOW() AS update_datetime
FROM tmp3
;

