-- 各カフェチェーンの情報を緯度経度ごとに、最新順に配列としてまとめる
WITH tmp1 AS (
    SELECT
        search_lat,
        search_lon,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag01 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp01,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag02 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp02,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag03 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp03,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag04 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp04,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag05 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp05,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag06 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp06,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag07 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp07,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag08 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp08,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag09 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp09,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag10 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp10,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag11 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp11,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag12 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp12,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag13 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp13,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag14 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp14,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag15 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp15,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag16 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp16,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag17 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp17,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag18 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp18,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag19 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp19,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag20 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp20,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag21 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp21,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag22 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp22,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag23 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp23,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag24 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp24,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag25 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp25,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag26 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp26,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag27 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp27,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag28 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp28,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag29 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp29,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag30 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp30,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag31 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp31,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag32 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp32,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag33 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp33,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag34 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp34,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag35 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp35,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag36 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp36,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag37 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp37,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag38 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp38,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag39 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp39,
        STRING_TO_ARRAY(STRING_AGG(CAST(cflag40 as TEXT), ',' ORDER BY update_datetime DESC), ',') AS ctmp40
    FROM
        :schema.str_stationcafe_info
    GROUP BY
        search_lat, search_lon
)

-- 駅カフェ情報最新データ抽出テーブルへの挿入
INSERT INTO :schema.tmp_filtering_newest_cafeinfo (
    search_lat,
    search_lon,
    cflag01,
    cflag02,
    cflag03,
    cflag04,
    cflag05,
    cflag06,
    cflag07,
    cflag08,
    cflag09,
    cflag10,
    cflag11,
    cflag12,
    cflag13,
    cflag14,
    cflag15,
    cflag16,
    cflag17,
    cflag18,
    cflag19,
    cflag20,
    cflag21,
    cflag22,
    cflag23,
    cflag24,
    cflag25,
    cflag26,
    cflag27,
    cflag28,
    cflag29,
    cflag30,
    cflag31,
    cflag32,
    cflag33,
    cflag34,
    cflag35,
    cflag36,
    cflag37,
    cflag38,
    cflag39,
    cflag40
)
-- 配列の1番目（一番最新）の情報を型変換して指定
SELECT
    search_lat,
    search_lon,
    CAST(ctmp01[1] AS INTEGER),
    CAST(ctmp02[1] AS INTEGER),
    CAST(ctmp03[1] AS INTEGER),
    CAST(ctmp04[1] AS INTEGER),
    CAST(ctmp05[1] AS INTEGER),
    CAST(ctmp06[1] AS INTEGER),
    CAST(ctmp07[1] AS INTEGER),
    CAST(ctmp08[1] AS INTEGER),
    CAST(ctmp09[1] AS INTEGER),
    CAST(ctmp10[1] AS INTEGER),
    CAST(ctmp11[1] AS INTEGER),
    CAST(ctmp12[1] AS INTEGER),
    CAST(ctmp13[1] AS INTEGER),
    CAST(ctmp14[1] AS INTEGER),
    CAST(ctmp15[1] AS INTEGER),
    CAST(ctmp16[1] AS INTEGER),
    CAST(ctmp17[1] AS INTEGER),
    CAST(ctmp18[1] AS INTEGER),
    CAST(ctmp19[1] AS INTEGER),
    CAST(ctmp20[1] AS INTEGER),
    CAST(ctmp21[1] AS INTEGER),
    CAST(ctmp22[1] AS INTEGER),
    CAST(ctmp23[1] AS INTEGER),
    CAST(ctmp24[1] AS INTEGER),
    CAST(ctmp25[1] AS INTEGER),
    CAST(ctmp26[1] AS INTEGER),
    CAST(ctmp27[1] AS INTEGER),
    CAST(ctmp28[1] AS INTEGER),
    CAST(ctmp29[1] AS INTEGER),
    CAST(ctmp30[1] AS INTEGER),
    CAST(ctmp31[1] AS INTEGER),
    CAST(ctmp32[1] AS INTEGER),
    CAST(ctmp33[1] AS INTEGER),
    CAST(ctmp34[1] AS INTEGER),
    CAST(ctmp35[1] AS INTEGER),
    CAST(ctmp36[1] AS INTEGER),
    CAST(ctmp37[1] AS INTEGER),
    CAST(ctmp38[1] AS INTEGER),
    CAST(ctmp39[1] AS INTEGER),
    CAST(ctmp40[1] AS INTEGER)
FROM tmp1
;

