#!/bin/bash

# ディレクトリのパスの最後に / は入れない
BATCH_DIR=$PROJECT_ROOT/batch
CONFIG_DIR=$PROJECT_ROOT/config
DATA_DIR=$PROJECT_ROOT/data
ENV_DIR=$PROJECT_ROOT/env
LOG_DIR=$PROJECT_ROOT/log
SSG_DIR=$PROJECT_ROOT/ssg
TMP_DIR=$PROJECT_ROOT/tmp
DB_SCHEMA_NAME=dev
